### ISSUE TITLE
Review documentation

### ISSUE THREAD

**Issue by dobrynya** [dobrynya/reajames#29]
Please review documentation in wiki and correct if unclear. Feel free to ask clarifications.

**Comment by Asamsig** [comment]
Under [Request reply integration pattern from a client's perspective](https://github.com/dobrynya/reajames/wiki/Request-reply-integration-pattern-from-a-client's-perspective) this line in the example:

```
val requestFactory = 
     (session: Session, req: ClientRequest) = session.createTextMessage(req.asText)
```

Is missing a `>`

So that is becomes:

```
val requestFactory = 
     (session: Session, req: ClientRequest) => session.createTextMessage(req.asText)
```

By the way I really like the documentation, it is very clean and concise. It has been a good experience using the library so far. Thanks!

**Comment by dobrynya** [comment]
Alexander thank you for review. Fixed a typo.
